# Generated by Django 4.1.1 on 2022-11-20 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('condition', models.CharField(choices=[('running', 'running'), ('broken', 'broken')], default='running', max_length=7)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_breakdown', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pointing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('axis', models.TextField()),
                ('distance', models.IntegerField()),
                ('station_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.spacestation')),
            ],
        ),
    ]
