# Generated by Django 4.1.1 on 2022-12-07 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_alter_pointing_axis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacestation",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 7, 10, 28, 52, 375863, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
