# Generated by Django 4.1.1 on 2022-12-07 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_alter_spacestation_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacestation",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
