version: "3.8"

services:
  postgres:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432

  backend:
    build:
      context: ./django
      dockerfile: Dockerfile.gunicorn
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./nginx/logs:/nginx/logs
    depends_on:
      - postgres
      - backend

volumes:
  postgres_data: